name: install_and_test
on: push
jobs:
  Ubuntu:
    name: Ubuntu Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: python3 -m pip install setuptools; python3 -m pip install "https://github.com/dpinney/multiplatform_pip/archive/refs/heads/main.zip"
      - name: Run Tests
        run: python3 -c "import mpp"
  macOS:
    name: macOS Tests
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: python3
      - name: Run tests
        run: python3
  Windows:
    name: Windows Tests
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: python
      - name: Run tests
        run: python
